version: '3'
services:
  db:
    image: postgres:alpine
    container_name: "banco-para-projeto-spring"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwe123
      PGDATA: /var/lib/postgresql/data/test
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
